#pragma once

#include "kernel1.cuh"
#include "kernel2.cuh"
#include "kernel3.cuh"
#include "kernel4.cuh"
#include "kernel5.cuh"
#include "kernel6.cuh"
#include "kernel7.cuh"
#include "my_kernel1.cuh"
#include "my_kernel2.cuh"
#include "my_kernel3.cuh"
#include "my_kernel4.cuh"
#include "my_kernel5.cuh"
#include "my_kernel6.cuh"
#include "my_kernel7.cuh"
